language: python
dist: xenial
sudo: required
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-server-dev-10  # for postgresql-libversion
env:
  global:
    - REPOLOGY_CONFIG=repology-test.conf.default
cache: pip
matrix:
  include:
    - python: 3.7
      env: COVERAGE=yes
    - python: 3.8-dev
    - python: nightly
  allow_failures:  # werkzeug incompatibility
    - python: 3.8-dev
    - python: nightly
before_install:
  - export REAL_PYTHON=$(basename $(dirname $(python-config --configdir)))
  - |-
    mkdir -p dep-libversion
    (
        cd dep-libversion &&
        wget -qO- https://github.com/repology/libversion/archive/master.tar.gz | tar -x -z -f- --strip-components 1 &&
        cmake . &&
        make &&
        sudo make install &&
        sudo ldconfig
    )
  - |-
    mkdir -p dep-html5-tidy
    (
        cd dep-html5-tidy
        wget -qO- https://github.com/htacg/tidy-html5/archive/master.tar.gz | tar -x -z -f- --strip-components 1 &&
        cmake . &&
        make &&
        sudo make install &&
        sudo ldconfig
    )
  - |-
    mkdir -p dep-postgresql-libversion
    (
        cd dep-postgresql-libversion &&
        wget -qO- https://github.com/repology/postgresql-libversion/archive/master.tar.gz | tar -x -z -f- --strip-components 1 &&
        make &&
        sudo make install
    )

  # install mandatory python dependencies
  - pip install Jinja2
  - pip install PyYAML
  - pip install flask
  - pip install libversion
  - pip install pillow
  - pip install psycopg2
  - pip install pytz

  # install extra python dependencies
  - pip install coveralls
  - pip install flake8
  - pip install flake8-builtins!=1.1.0
  - pip install flake8-import-order
  - pip install flake8-quotes
  - pip install mypy>=0.720
  - pip install pytidylib # uses newer libtidy installed above
before_script:
  - export REPOLOGY_CONFIG=./repology-test.conf.default
  - sudo -u postgres psql -c "CREATE DATABASE repology_test;"
  - sudo -u postgres psql -c "CREATE USER repology_test WITH PASSWORD 'repology_test'"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE repology_test TO repology_test"
  - sudo -u postgres psql -d repology_test -c "CREATE EXTENSION IF NOT EXISTS pg_trgm"
  - sudo -u postgres psql -d repology_test -c "CREATE EXTENSION IF NOT EXISTS libversion"
  - psql -U repology_test < testdata/repology_test.sql
  - echo "BADGE_FONT = '/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf'" >> $REPOLOGY_CONFIG
  - echo "BADGE_FONT_BOLD = '/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf'" >> $REPOLOGY_CONFIG
script:
  # test all target
  - make

  # check python syntax
  - make flake8

  # check python types
  - make mypy

  # run unit tests with coverage
  - coverage run --source=repologyapp -m unittest discover

after_success:
  - if [ -n "$COVERAGE" ]; then coveralls; fi
